DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_METRIC_TYPES" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Code" NVARCHAR2(30) NOT NULL,
        "Name" NVARCHAR2(80) NOT NULL,
        "Unit" NVARCHAR2(20) NOT NULL,
        "Description" NVARCHAR2(300),
        "NominalMin" BINARY_DOUBLE,
        "NominalMax" BINARY_DOUBLE,
        CONSTRAINT "PK_METRIC_TYPE" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_REGIONS" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Code" NVARCHAR2(30) NOT NULL,
        "Name" NVARCHAR2(120) NOT NULL,
        "ModuleType" NVARCHAR2(60),
        "OrbitalSegment" NVARCHAR2(120),
        "Description" NVARCHAR2(500),
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        CONSTRAINT "PK_REGION" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_USERS" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Email" NVARCHAR2(150) NOT NULL,
        "PasswordHash" NVARCHAR2(300) NOT NULL,
        "Role" NVARCHAR2(30) NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        CONSTRAINT "PK_USER" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_ALERT_RULES" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Name" NVARCHAR2(120) NOT NULL,
        "Description" NVARCHAR2(300),
        "MetricTypeId" NUMBER(10) NOT NULL,
        "RegionId" NUMBER(10),
        "MinThreshold" BINARY_DOUBLE,
        "MaxThreshold" BINARY_DOUBLE,
        "Severity" NVARCHAR2(20) NOT NULL,
        "IsActive" NUMBER(1) NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        CONSTRAINT "PK_ALERT_RULE" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RULE_METRIC" FOREIGN KEY ("MetricTypeId") REFERENCES "OGH_METRIC_TYPES" ("Id"),
        CONSTRAINT "FK_RULE_REGION" FOREIGN KEY ("RegionId") REFERENCES "OGH_REGIONS" ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_DEVICES" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Identifier" NVARCHAR2(50) NOT NULL,
        "Name" NVARCHAR2(120) NOT NULL,
        "DeviceType" NVARCHAR2(60),
        "Status" NVARCHAR2(20) NOT NULL,
        "FirmwareVersion" NVARCHAR2(30),
        "InstalledAt" TIMESTAMP(7) NOT NULL,
        "LastSeenAt" TIMESTAMP(7),
        "RegionId" NUMBER(10) NOT NULL,
        CONSTRAINT "PK_DEVICE" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DEVICE_REGION" FOREIGN KEY ("RegionId") REFERENCES "OGH_REGIONS" ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_SENSOR_READINGS" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "CollectedAt" TIMESTAMP(7) NOT NULL,
        "ReceivedAt" TIMESTAMP(7) NOT NULL,
        "SourceFile" NVARCHAR2(150),
        "DeviceId" NUMBER(10) NOT NULL,
        CONSTRAINT "PK_READING" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_READING_DEVICE" FOREIGN KEY ("DeviceId") REFERENCES "OGH_DEVICES" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_MEASUREMENTS" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Value" BINARY_DOUBLE NOT NULL,
        "SensorReadingId" NUMBER(10) NOT NULL,
        "MetricTypeId" NUMBER(10) NOT NULL,
        CONSTRAINT "PK_MEASUREMENT" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MEAS_METRIC" FOREIGN KEY ("MetricTypeId") REFERENCES "OGH_METRIC_TYPES" ("Id"),
        CONSTRAINT "FK_MEAS_READING" FOREIGN KEY ("SensorReadingId") REFERENCES "OGH_SENSOR_READINGS" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "OGH_ALERTS" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Message" NVARCHAR2(400) NOT NULL,
        "Severity" NVARCHAR2(20) NOT NULL,
        "Status" NVARCHAR2(20) NOT NULL,
        "TriggeredValue" BINARY_DOUBLE NOT NULL,
        "CreatedAt" TIMESTAMP(7) NOT NULL,
        "AcknowledgedAt" TIMESTAMP(7),
        "ResolvedAt" TIMESTAMP(7),
        "AlertRuleId" NUMBER(10),
        "MetricTypeId" NUMBER(10) NOT NULL,
        "MeasurementId" NUMBER(10),
        "DeviceId" NUMBER(10) NOT NULL,
        "RegionId" NUMBER(10) NOT NULL,
        "AcknowledgedByUserId" NUMBER(10),
        CONSTRAINT "PK_ALERT" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ALERT_DEVICE" FOREIGN KEY ("DeviceId") REFERENCES "OGH_DEVICES" ("Id"),
        CONSTRAINT "FK_ALERT_MEAS" FOREIGN KEY ("MeasurementId") REFERENCES "OGH_MEASUREMENTS" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ALERT_METRIC" FOREIGN KEY ("MetricTypeId") REFERENCES "OGH_METRIC_TYPES" ("Id"),
        CONSTRAINT "FK_ALERT_REGION" FOREIGN KEY ("RegionId") REFERENCES "OGH_REGIONS" ("Id"),
        CONSTRAINT "FK_ALERT_RULE" FOREIGN KEY ("AlertRuleId") REFERENCES "OGH_ALERT_RULES" ("Id"),
        CONSTRAINT "FK_ALERT_USER" FOREIGN KEY ("AcknowledgedByUserId") REFERENCES "OGH_USERS" ("Id") ON DELETE SET NULL
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    BEGIN
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (1, N'TEMPERATURE', N'Ambient air temperature inside the growth module.', N'Air Temperature', 26.0E0d, 18.0E0d, N'C');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (2, N'HUMIDITY', N'Relative air humidity.', N'Relative Humidity', 80.0E0d, 50.0E0d, N'%');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (3, N'CO2', N'Carbon dioxide concentration available for photosynthesis.', N'Carbon Dioxide', 1200.0E0d, 400.0E0d, N'ppm');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (4, N'O2', N'Oxygen concentration in the cabin atmosphere.', N'Oxygen', 23.0E0d, 19.0E0d, N'%');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (5, N'LUMINOSITY', N'Photosynthetically active radiation reaching the canopy.', N'Photosynthetic Light', 800.0E0d, 200.0E0d, N'umol/m2/s');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (6, N'SOIL_MOISTURE', N'Water content of the growing substrate.', N'Substrate Moisture', 70.0E0d, 40.0E0d, N'%');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (7, N'PH', N'Acidity of the hydroponic nutrient solution.', N'Nutrient Solution pH', 6.5E0d, 5.5E0d, N'pH');
    INSERT INTO "OGH_METRIC_TYPES" ("Id", "Code", "Description", "Name", "NominalMax", "NominalMin", "Unit")
    VALUES (8, N'EC', N'Electrical conductivity (nutrient strength) of the solution.', N'Nutrient Conductivity', 2.4E0d, 1.2E0d, N'mS/cm');
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERT_RULES_MetricTypeId" ON "OGH_ALERT_RULES" ("MetricTypeId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERT_RULES_RegionId" ON "OGH_ALERT_RULES" ("RegionId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_ALERT_STATUS" ON "OGH_ALERTS" ("Status")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_AcknowledgedByUserId" ON "OGH_ALERTS" ("AcknowledgedByUserId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_AlertRuleId" ON "OGH_ALERTS" ("AlertRuleId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_DeviceId" ON "OGH_ALERTS" ("DeviceId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_MeasurementId" ON "OGH_ALERTS" ("MeasurementId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_MetricTypeId" ON "OGH_ALERTS" ("MetricTypeId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_ALERTS_RegionId" ON "OGH_ALERTS" ("RegionId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_OGH_DEVICES_RegionId" ON "OGH_DEVICES" ("RegionId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_DEVICE_IDENT" ON "OGH_DEVICES" ("Identifier")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_MEAS_METRIC" ON "OGH_MEASUREMENTS" ("MetricTypeId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_MEAS_READING" ON "OGH_MEASUREMENTS" ("SensorReadingId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_METRIC_CODE" ON "OGH_METRIC_TYPES" ("Code")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_REGION_CODE" ON "OGH_REGIONS" ("Code")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_READING_DEVICE" ON "OGH_SENSOR_READINGS" ("DeviceId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_USER_EMAIL" ON "OGH_USERS" ("Email")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604135925_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260604135925_InitialCreate'', N''9.0.9'')'
    ;
 END IF;
END;

/

