// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitalGreenhouse.Api.Data;

#nullable disable

namespace OrbitalGreenhouse.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("MeasurementId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RegionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<double>("TriggeredValue")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id")
                        .HasName("PK_ALERT");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ALERT_STATUS");

                    b.ToTable("OGH_ALERTS", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id")
                        .HasName("PK_ALERT_RULE");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("RegionId");

                    b.ToTable("OGH_ALERT_RULES", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<int>("RegionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id")
                        .HasName("PK_DEVICE");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("UX_DEVICE_IDENT");

                    b.HasIndex("RegionId");

                    b.ToTable("OGH_DEVICES", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SensorReadingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Value")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id")
                        .HasName("PK_MEASUREMENT");

                    b.HasIndex("MetricTypeId")
                        .HasDatabaseName("IX_MEAS_METRIC");

                    b.HasIndex("SensorReadingId")
                        .HasDatabaseName("IX_MEAS_READING");

                    b.ToTable("OGH_MEASUREMENTS", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<double?>("NominalMax")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("NominalMin")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id")
                        .HasName("PK_METRIC_TYPE");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_METRIC_CODE");

                    b.ToTable("OGH_METRIC_TYPES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TEMPERATURE",
                            Description = "Ambient air temperature inside the growth module.",
                            Name = "Air Temperature",
                            NominalMax = 26.0,
                            NominalMin = 18.0,
                            Unit = "C"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HUMIDITY",
                            Description = "Relative air humidity.",
                            Name = "Relative Humidity",
                            NominalMax = 80.0,
                            NominalMin = 50.0,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CO2",
                            Description = "Carbon dioxide concentration available for photosynthesis.",
                            Name = "Carbon Dioxide",
                            NominalMax = 1200.0,
                            NominalMin = 400.0,
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 4,
                            Code = "O2",
                            Description = "Oxygen concentration in the cabin atmosphere.",
                            Name = "Oxygen",
                            NominalMax = 23.0,
                            NominalMin = 19.0,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LUMINOSITY",
                            Description = "Photosynthetically active radiation reaching the canopy.",
                            Name = "Photosynthetic Light",
                            NominalMax = 800.0,
                            NominalMin = 200.0,
                            Unit = "umol/m2/s"
                        },
                        new
                        {
                            Id = 6,
                            Code = "SOIL_MOISTURE",
                            Description = "Water content of the growing substrate.",
                            Name = "Substrate Moisture",
                            NominalMax = 70.0,
                            NominalMin = 40.0,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 7,
                            Code = "PH",
                            Description = "Acidity of the hydroponic nutrient solution.",
                            Name = "Nutrient Solution pH",
                            NominalMax = 6.5,
                            NominalMin = 5.5,
                            Unit = "pH"
                        },
                        new
                        {
                            Id = 8,
                            Code = "EC",
                            Description = "Electrical conductivity (nutrient strength) of the solution.",
                            Name = "Nutrient Conductivity",
                            NominalMax = 2.3999999999999999,
                            NominalMin = 1.2,
                            Unit = "mS/cm"
                        });
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ModuleType")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("OrbitalSegment")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.HasKey("Id")
                        .HasName("PK_REGION");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_REGION_CODE");

                    b.ToTable("OGH_REGIONS", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id")
                        .HasName("PK_READING");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_READING_DEVICE");

                    b.ToTable("OGH_SENSOR_READINGS", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_USER_EMAIL");

                    b.ToTable("OGH_USERS", (string)null);
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Alert", b =>
                {
                    b.HasOne("OrbitalGreenhouse.Api.Models.User", "AcknowledgedByUser")
                        .WithMany("AcknowledgedAlerts")
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ALERT_USER");

                    b.HasOne("OrbitalGreenhouse.Api.Models.AlertRule", "AlertRule")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ALERT_RULE");

                    b.HasOne("OrbitalGreenhouse.Api.Models.Device", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ALERT_DEVICE");

                    b.HasOne("OrbitalGreenhouse.Api.Models.Measurement", "Measurement")
                        .WithMany("Alerts")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ALERT_MEAS");

                    b.HasOne("OrbitalGreenhouse.Api.Models.MetricType", "MetricType")
                        .WithMany()
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ALERT_METRIC");

                    b.HasOne("OrbitalGreenhouse.Api.Models.Region", "Region")
                        .WithMany("Alerts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ALERT_REGION");

                    b.Navigation("AcknowledgedByUser");

                    b.Navigation("AlertRule");

                    b.Navigation("Device");

                    b.Navigation("Measurement");

                    b.Navigation("MetricType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.AlertRule", b =>
                {
                    b.HasOne("OrbitalGreenhouse.Api.Models.MetricType", "MetricType")
                        .WithMany("AlertRules")
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RULE_METRIC");

                    b.HasOne("OrbitalGreenhouse.Api.Models.Region", "Region")
                        .WithMany("AlertRules")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RULE_REGION");

                    b.Navigation("MetricType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Device", b =>
                {
                    b.HasOne("OrbitalGreenhouse.Api.Models.Region", "Region")
                        .WithMany("Devices")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DEVICE_REGION");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Measurement", b =>
                {
                    b.HasOne("OrbitalGreenhouse.Api.Models.MetricType", "MetricType")
                        .WithMany("Measurements")
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MEAS_METRIC");

                    b.HasOne("OrbitalGreenhouse.Api.Models.SensorReading", "SensorReading")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEAS_READING");

                    b.Navigation("MetricType");

                    b.Navigation("SensorReading");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.SensorReading", b =>
                {
                    b.HasOne("OrbitalGreenhouse.Api.Models.Device", "Device")
                        .WithMany("Readings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_READING_DEVICE");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.AlertRule", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Device", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Measurement", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.MetricType", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.Region", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Alerts");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.SensorReading", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("OrbitalGreenhouse.Api.Models.User", b =>
                {
                    b.Navigation("AcknowledgedAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
